highlighter: rouge
permalink: none
kramdown:
  input: GFM
  hard_wrap: false
repository: jasheldo/jasheldo.github.io
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
google_analytics: 'GTM-PLQ4F6G'
title: Jim
description: Jim's portfolio and writings on machine learning, data science and mathematics.
url: http://www.jimsheldon.us
author: James Sheldon
twitter:
  username: jasheldo
logo: images/contents/NN.png
social:
  name: Jim
  links:
    - https://twitter.com/jasheldo
    - https://www.linkedin.com/in/jimsheldon
    - https://github.com/jasheldo